name: GitHub Action Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 23f3001752@ds.study.iitm.ac.in
        run: echo "Hello, world!"
